#!/bin/bash

# Author: Jacob M
# Last modified: 2/14/2024
# Educational purposes only

# Basic menu to help manage docker-compose images and containers
# Run as sudo

# Sets user home, $HOME jumps to roots home dir so you cant utilize it
USER_HOME=$(eval echo ~${SUDO_USER})


# Menu to update, restart, and pull on docker.

function Update_Docker() {
    echo ""
cd ${USER_HOME}/docker_torrents && docker-compose up -d
}

function Restart_Docker() {
    echo ""
cd ${USER_HOME}/docker_torrents && docker-compose restart
}

function Pull_Docker() {
    echo ""
cd ${USER_HOME}/docker_torrents && docker-compose pull
}

function Docker_PS() {
    echo ""
cd ${USER_HOME}/docker_torrents && docker ps
}

##
# Color  Variables
##
green='\e[32m'
blue='\e[34m'
clear='\e[0m'
red='\e[31m'

##
# Color Functions
##

ColorGreen(){
	echo -ne $green$1$clear
}
ColorBlue(){
	echo -ne $blue$1$clear
}

menu(){
echo -ne "
Docker Menu
$(ColorGreen '1)') Update Docker
$(ColorGreen '2)') Restart Docker
$(ColorGreen '3)') Pull from DockerHub 
$(ColorGreen '4)') Docker ps
$(ColorGreen '0)') Exit
$(ColorBlue 'Choose an option:') "
        read a
        case $a in
	        1) Update_Docker ; menu ;;
	        2) Restart_Docker ; menu ;;
	        3) Pull_Docker ; menu ;;
	        4) Docker_PS ; menu ;;
		0) exit 0 ;;
		*) echo -e "${red}Not an option.${clear}; WrongCommand;;
        esac
}

# Call the menu function
menu
