#!/bin/bash

# Author: Jacob M
# Last edited on: 2/14/2024

# Menu for automating and managing your entire environment through a script.


########### Color Functions ###########

green='\e[32m'
red='\e[31m'
clear='\e[0m'

############################################################################################

function docker_c
{
 option=0
 until [ "$option" = "4" ]; do
 echo -e "${green}  1.)${clear} Show Containers"
 echo -e "${green}  2.)${clear} Compose Pull"
 echo -e "${green}  3.)${clear} Compose Update"
 echo -e "${green}  4.)${clear} Return to menu"

 echo -n "Enter choice: "
 read option
 printf '\n%.0s' `seq 1 40`
 case $option in
 1 ) docker ps;;
 2 ) docker-compose pull;;
 3 ) docker-compose up -d ;;
 4 ) main_menu ;;
 * )  echo -e "${red}Please make a valid Docker selection!"${clear}
 esac
#   }
 done
}
############################################################################################

function kubernetes_c 
{
 option=0
 until [ "$option" = "4" ]; do
 echo -e "${green}  1.)${clear} Get Pods"
 echo -e "${green}  2.)${clear} Get Services"
 echo -e "${green}  3.)${clear} Get Version"
 echo -e "${green}  4.)${clear} Return to menu"

 echo -n "Enter choice: "
 read option
 printf '\n%.0s' `seq 1 40`
 case $option in
 1 ) microk8s kubectl get pods ;;
 2 ) microk8s kubectl get services ;;
 3 ) microk8s kubectl version ;;
 4 ) main_menu; press_enter ;;
 * ) echo -e "${red}Please make a valid Kubernetes selection!"${clear}
 esac
#   }
 done
}
############################################################################################

function pterodactyl_c
{
 option=0
 until [ "$option" = "4" ]; do
 echo -e "${green}  1.)${clear} Wings Status"
 echo -e "${green}  2.)${clear} Wings On"
 echo -e "${green}  3.)${clear} Wings Off"
 echo -e "${green}  4.)${clear} Return to menu"

 echo -n "Enter choice: "
 read option
 printf '\n%.0s' `seq 1 40`
 case $option in
 1 ) systemctl status wings ;;
 2 ) systemctl start wings ;;
 3 ) systemctl stop wings ;;
 4 ) main_menu; press_enter ;;
 * ) echo -e "${red}Please make a valid Pterodactyl selection!"${clear}
 esac
#   }
 done
}
############################################################################################

function main_menu 
{
option=0
until [ "$option" = "5" ]; do
echo -e "${green}  1.)${clear} Docker Commands"
echo -e "${green}  2.)${clear} Kubernetes Commands"
echo -e "${green}  3.)${clear} Pterodactyl Commands"
echo -e "${green}  4.)${clear} System Resources"
echo -e "${green}  5.)${clear} Quit"

echo -n "Enter choice: "
read option
printf '\n%.0s' `seq 1 40`
case $option in
    1 ) docker_c; press_enter ;;                       # docker commands
    2 ) kubernetes_c; press_enter ;;                   # kubernetes commands
    3 ) pterodactyl_c; press_enter ;;                  # pterodactly commands
    4 ) lsblk; free; printf '\n%.0s' `seq 1 3` ;;      # sys resources
    5 ) exit;;
    * ) echo -e "${red}Please make a valid selection!"${clear}
esac
done
 }

main_menu
