#!/bin/bash

# Author: Jacob M
# Last edited on: 2/15/2024

######Unfinished#######
# Kubernetes YAML creation tool for Namespace, Pods, Roles, and Deployments.

echo -n "" > K8.yaml

read -t 60 -p 'Input the kind of K8 YAML, ex: Deployment, Pod, Role, Namespace, Service:' kind
if [ ${kind} = Role ]; then
apiversion=rbac.authorization.k8s.io/
else
apiversion=
fi

echo "apiVersion: ${apiversion}v1
kind: ${kind}" >> K8.yaml

cat K8.yaml
printf '\n%.0s' `seq 1 5`

read -t 60 -p 'Input the name under metadata:' name
cat K8.yaml
printf '\n%.0s' `seq 1 5`

echo "metadata:
  name: ${name}" >> K8.yaml

if [ ${kind} != Namespace ]; then
microk8s kubectl get namespace
read -t 60 -p 'Input the Namespace under metadata:' namespace
echo "  namespace: ${namespace}" >> K8.yaml
else
echo "  labels:
    name: ${name}" >> K8.yaml
cat K8.yaml
printf '\n%.0s' `seq 1 5`
echo "Namespace complete"
exit
fi

cat K8.yaml
printf '\n%.0s' `seq 1 5`

# q used inside an echo command with {"} is problematic so q is defined as {"} 
q='"'

if [ ${kind} = Role ]; then
set -f
read -t 60 -p 'Do you have an apiGroup ? leave blank if no, put in quotes:' apigroup
read -t 60 -p 'What are your resources ? ex. pods, nodes, deployments, services, crontabs, jobs, or *. Put in quotes:' resources
read -t 60 -p 'What are your resourceNames ? Put in quotes:' resourcenames
read -t 60 -p 'What are your verbs ? ex. get, list, watch, create, update, patch, delete, or *. Put in quotes with a comma as seperation:' verb

verbs=$( echo $verb | sed -e 's/ /", "/g' )

echo "rules:
- apiGroups: [ ${apigroup} ]
  resources: [ ${resources} ]
  resourceNames: [ "\""${resourcenames}"\"" ]
  verbs: [ ${q}${verbs}${q} ]" >> K8.yaml

set +f

fi





exit
