#!/bin/bash

# Author: Jacob M
# Last edited on: 1/27/2024

# script used to pull from a file and ping each host.

# If parameters dont equal 1 then exit
if [[ $# -ne 1 ]]
    then
    echo "$0 needs a parameter for where the list is located"
    exit 1
fi

# wipe file or create if not there
echo -n "" > outputfile.txt
echo -n "" > success.txt
echo -n "" > timeout.txt

# remove file in /tmp/ and throw output in bin, file is used to stop runaway script
rm -f /tmp/stopit 2>/dev/null

cat "$1" | while read line

do

# send ping to /dev/null and send output to where input goes
if ping -c 2 -W2 $line > /dev/null 2>&1
  then
# echo then put in these files:
  echo "$line successful" | tee -a 'successful.txt' 
  else
  echo "$line timeout" | tee -a 'timeout.txt'
fi

# if script is runaway do 'touch /tmp/stopit' to stop script
[ -f /tmp/stopit ] && break 
done > 'outputfile.txt'
