#!/bin/bash

# Author: Jacob M
# Last edited on: 1/27/2024

# Update for pterodactyl automated by simple_update.yml in ansible playbooks
# Ensure to use root or sudo

# Creates pterodactly log file
touch ${HOME}/ptero_logs.txt
cd /var/www/pterodactyl

php artisan down || echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
# Dependency, if last command didnt work then echo reason for failure in log file

curl -L https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz | tar -xzv
chmod -R 755 storage/* bootstrap/cache
composer install --no-dev --optimize-autoloader
php artisan view:clear
php artisan config:clear
php artisan migrate --seed --force
chown -R www-data:www-data /var/www/pterodactyl/*

php artisan queue:restart || echo "$? failed" | tee -a ${HOME}/ptero_logs.txt
# Dependency, if last command didnt work then echo reason for failure in log file

php artisan up || echo "$? failed" | tee -a ${HOME}/ptero_logs.txt

systemctl stop wings || echo "$? failed" | tee -a ${HOME}/ptero_logs.txt

curl -L -o /usr/local/bin/wings "https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_$([[ "$(uname -m)" == "x86_64" ]] && echo "amd64" || echo "arm64")"
chmod u+x /usr/local/bin/wings

systemctl restart wings || echo "$? failed" | tee -a ${HOME}/ptero_logs.txt

echo "Update finished successfully!"
