#!/bin/bash
# change 'apt' to Linux OS of choice
# run as root to avoid sudo 
apt update
apt upgrade

#path to docker dir
cd /home/torrent/docker_torrents
docker-compose down

#pulling new images
docker-compose pull
docker-compose up -d
echo "docker update complete"
