#!/bin/bash

# Author: Jacob M
# Last edited on: 1/27/2024

# add name of server you want to backup as first option when running script.
# ex. "./simple_server-backup game" will output "game_backup_(current date).tar.gz"

# ensure you mount all partitions or backup will not complete
# add folders you dont want backedup in list below

read -t 60 -p 'Input the server name:' server

echo "starting backup"

date=$(date '+%Y-%m-%d')

# sets so you can see all the output of files being tar balled
set -x

sudo tar -czf /mnt/Media/"${server}_backup_${date}.tar.gz" \
    --exclude=/dev \
    --exclude=/mnt \
    --exclude=/proc \
    --exclude=/sys \
    --exclude=/tmp \
    --exclude=/media \
    --exclude=/lost+found \
    --exclude=/var/log \
    --exclude=/home/torrent/docker_torrents/mnt \
    /

# sets so you dont have to see the rest of the output
set +x

# if you can cd into backup directory then move the recent backup to that directory, and delete old backups else skip
if cd /mnt/Media/backup
    then
    mv /mnt/Media/"${server}_backup_$date.tar.gz" /mnt/Media/backup/
# deletes backup older than 3 months
    find /mnt/Media/backup/*.tar.gz -mmin +131400 -delete
    chmod 744 /mnt/Media/backup/*.tar.gz
    else
    echo "no backup directory mounted, skipping"
fi

echo "backup complete"
