#!/bin/bash

# Author: Jacob M
# Last edited on: 1/27/2024

# Simple check of your cpu idle useage to determine if you're overloaded.
# Attach to a cron job for automation

# Make a variable called cpu and run the command to check usage, if the 8th column (cpu idle) is higher than 51% then print low, else print high for high usage. 
cpu=$(top -n1 | awk '/^%Cpu/{if ($8 > 50)    {print "low"}    else {print "high"} }')
  
# Make a variable with hostname cutting out all the extra stuff, might need to tweak based on user preference.
host=$(hostname -s | cut -d'.'-f 1 | tr '[:upper:]' '[:lower:]')

# Throw ouput into .txt for graphical analysis
touch "${HOME}/cpu_graphic.txt"
echo "$cpu" >> "${HOME}/cpu_graphic.txt"

# Make a variable called date with the date in year, month, day format and hour, minute, second format.
date=$(date '+%Y-%m-%d %H:%M:%S')

# If the CPU is labeled as "high" from 'awk' then put info in warning.txt in certain directory, else echo to CLI.
if [ "$cpu" = "high" ]
  then
  echo "$host $date CPU overloaded" >> /home/user/warning.txt
  else
  echo "No issues with CPU utilization on $date"
fi

# Delete anything 31 lines and older. Preps for gnuplot-graphic script
# 31,$ means the range line 31 until the end, and d means to delete. Only the first 30 lines will remain. The -i flag tells sed to edit the file in-place.
sed -i '31,$d' /home/user/cpu_graphic.txt
