#!/bin/bash

# Author: Jacob M
# Last edited on: 1/27/2024
# Educational purposes only

# change 'apt' to Linux OS of choice
# run as root or sudo 

apt update
apt upgrade

#path to docker dir
cd ${HOME}/docker_torrents
docker-compose down

# Pulling new images
docker-compose pull
if
  [ $? -eq 0 ]
then 
  echo "pull successful"
else
  echo "$? failed"
  exit
fi

docker-compose up -d
echo "docker update complete"
