#!/bin/bash

# Author: Jacob M
# Last edited on: 1/23/2024
# Educational purposes only

# change 'apt' to Linux OS of choice
# run as root to avoid sudo 
apt update
apt upgrade

#path to docker dir
cd /home/torrent/docker_torrents
docker-compose down

#pulling new images
docker-compose pull
if
  [ $? -eq 0]
then 
  echo "pull successful"
else
  echo "$? failed"
  exit
fi

docker-compose up -d
echo "docker update complete"
